apiVersion: apps/v1
kind: Deployment
metadata:
  name: medifollow-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medifollow-backend
  template:
    metadata:
      labels:
        app: medifollow-backend
    spec:
      containers:
      - name: medifollow-backend
        image: yahyakaroui/medifollow-backend:latest
        ports:
        - containerPort: 3000

        # 🔥 AJOUT CRUCIAL
        envFrom:
          - secretRef:
              name: backend-env