services:
  - type: web
    name: medifollow-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --production=false && npm run build
    startCommand: node /opt/render/project/src/dist/main.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: EMAIL_HOST
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://medifollow.vercel.app
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
